name = "MPITape"
uuid = "0eb6d5be-9499-4b92-a3d2-b4957f471b2b"
authors = ["Carsten Bauer <carsten.bauer@uni-paderborn.de> and contributors"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Kroki = "b3565e16-c1f2-4fe9-b4ab-221c88942068"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Cassette = "0.3"
DocStringExtensions = "0.9"
MPI = "0.20"
MPIPreferences = "0.1"
MacroTools = "0.5"
julia = "1.8"

[extras]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MPI", "MPIPreferences"]
